import type { Metadata } from "next";
import localFont from "next/font/local"
import "./globals.css";
import { cn } from "@/lib/utils";
import { TooltipProvider } from "@/components/ui/tooltip";
import SideBar from "@/components/SideBar";
import { ThemeProvider } from "next-themes";

const prospec = localFont({
  src: [
    {
      path: "../../public/fonts/Prospec.otf",
    },
    // {
    //   path : "../../public/fonts/Prospec-Outline.otf",
    // }
  ],
  adjustFontFallback: 'Arial',
  preload: true,
  variable: '--font-prospec'
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scroll-smooth">
      <body className={cn(
        "",
        prospec.variable
      )}
      >
        <ThemeProvider attribute="class">
          <TooltipProvider>
            <SideBar />
            {children}
          </TooltipProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
